package dtsa.mapper.util.exception;


public class RescueFacility {
// Rescue
	public static <T extends Exception> void attempt (Runnable aTask, int aCount) {
		
	}
}
